import { BrandList } from '../../types';

type ManufacturerData = {
  category: number;
  name: string;
  icon?: {
    name: string;
    type?: 'font-awesome' | 'material';
  };
};

export const manufacturerData: ManufacturerData[] = [
  { category: 0x000, name: 'Unknown', icon: { name: 'bath', type: 'font-awesome' } },
  { category: 0x001, name: 'Phone', icon: { name: 'smartphone' } },
  { category: 0x002, name: 'Computer', icon: { name: 'computer' } },
  { category: 0x003, name: 'Watch', icon: { name: 'watch' } },
  { category: 0x004, name: 'Clock', icon: { name: 'alarm' } },
  { category: 0x005, name: 'Display', icon: { name: 'personalvideo' } },
  { category: 0x006, name: 'RemoteControl', icon: { name: 'settingsremote' } },
  { category: 0x007, name: 'Eye-glasses', icon: { name: 'house' } },
  { category: 0x008, name: 'Tag', icon: { name: 'label' } },
  { category: 0x009, name: 'Keyring', icon: { name: 'datausage' } },
  { category: 0x00a, name: 'Media Player', icon: { name: 'permmedia' } },
  { category: 0x00b, name: 'Barcode Scanner', icon: { name: 'viewweek' } },
  {
    category: 0x00c,
    name: 'Thermometer',
    icon: { name: 'thermometer-quater', type: 'font-awesome' },
  },
  { category: 0x00d, name: 'Heart Rate Sensor', icon: { name: 'house' } },
  { category: 0x00e, name: 'Blood Pressure', icon: { name: 'house' } },
  { category: 0x00f, name: 'Human Interface Device', icon: { name: 'house' } },
  { category: 0x010, name: 'Glucose Meter', icon: { name: 'house' } },
  { category: 0x011, name: 'Running Walking Sensor', icon: { name: 'house' } },
  { category: 0x012, name: 'Cycling', icon: { name: 'house' } },
  { category: 0x013, name: 'Control Device', icon: { name: 'house' } },
  { category: 0x014, name: 'Network Device', icon: { name: 'house' } },
  { category: 0x015, name: 'Sensor', icon: { name: 'house' } },
  { category: 0x016, name: 'Light Fixtures', icon: { name: 'house' } },
  { category: 0x017, name: 'Fan', icon: { name: 'house' } },
  { category: 0x018, name: 'HVAC', icon: { name: 'house' } },
  { category: 0x019, name: 'Air Conditioning', icon: { name: 'house' } },
  { category: 0x01a, name: 'Humidifier', icon: { name: 'house' } },
  { category: 0x01b, name: 'Heating', icon: { name: 'house' } },
  { category: 0x01c, name: 'Access Control', icon: { name: 'house' } },
  { category: 0x01d, name: 'Motorized Device', icon: { name: 'house' } },
  { category: 0x01e, name: 'Power Device', icon: { name: 'house' } },
  { category: 0x01f, name: 'Light Source', icon: { name: 'house' } },
  { category: 0x020, name: 'Window Covering', icon: { name: 'house' } },
  { category: 0x021, name: 'Audio Sink', icon: { name: 'house' } },
  { category: 0x022, name: 'Audio Source', icon: { name: 'house' } },
  { category: 0x023, name: 'Motorized Vehicle', icon: { name: 'house' } },
  { category: 0x024, name: 'Domestic Appliance', icon: { name: 'house' } },
  { category: 0x025, name: 'Wearable Audio Device', icon: { name: 'house' } },
  { category: 0x026, name: 'Aircraft', icon: { name: 'house' } },
  { category: 0x027, name: 'AV Equipment', icon: { name: 'house' } },
  { category: 0x028, name: 'Display Equipment', icon: { name: 'house' } },
  { category: 0x029, name: 'Hearing aid', icon: { name: 'house' } },
  { category: 0x02a, name: 'Gaming', icon: { name: 'house' } },
  { category: 0x02b, name: 'Signage', icon: { name: 'house' } },
  { category: 0x031, name: 'Pulse Oximeter', icon: { name: 'house' } },
  { category: 0x032, name: 'Weight Scale', icon: { name: 'house' } },
  { category: 0x033, name: 'Personal Mobility Device', icon: { name: 'house' } },
  { category: 0x034, name: 'Continuous Glucose Monitor', icon: { name: 'house' } },
  { category: 0x035, name: 'Insulin Pump', icon: { name: 'house' } },
  { category: 0x036, name: 'Medication Delivery', icon: { name: 'house' } },
  { category: 0x037, name: 'Spirometer', icon: { name: 'house' } },
  { category: 0x051, name: 'Outdoor Sports Activity', icon: { name: 'house' } },
];

export const brands: BrandList = {
  '00C4': { name: 'LG Electronics', iconName: 'lg' },
  '0601': { name: 'Schrader Electronics', iconName: 'lg' },
  '000D': { name: 'Texas Instruments Inc.', iconName: 'TI' },
  FFF0: { name: 'Texas Instruments Inc.', iconName: 'TI' },
  FFC0: { name: 'Texas Instruments Inc.', iconName: 'TI' },
  FCAA: { name: 'Spintly, Inc.' },
  FCAB: { name: 'IRISS INC.' },
  FCAC: { name: 'IRISS INC.' },
  FCAD: { name: 'Beijing 99help Safety Technology Co., Ltd' },
  FCAE: { name: 'Imagine Marketing Limited' },
  FCAF: { name: 'AltoBeam Inc.' },
  FCB0: { name: 'Ford Motor Company' },
  FCB1: { name: 'Google LLC', iconName: 'google' },
  FCB2: { name: 'Apple Inc.', iconName: 'apple' },
  FCB3: { name: 'SWEEN' },
  FCB4: { name: 'OMRON HEALTHCARE Co., Ltd.' },
  FCB5: { name: 'OMRON HEALTHCARE Co., Ltd.' },
  FCB6: { name: 'OMRON HEALTHCARE Co., Ltd.' },
  FCB7: { name: 'T-Mobile USA' },
  FCB8: { name: 'Ribbiot, INC.' },
  FCB9: { name: 'Lumi United Technology Co., Ltd' },
  FCBA: { name: 'BlueID GmbH' },
  FCBB: { name: 'SharkNinja Operating LLC' },
  FCBC: { name: 'Drowsy Digital, Inc.' },
  FCBD: { name: 'Toshiba Corporation', iconName: 'toshiba' },
  FCBE: { name: 'Musen Connect, Inc.' },
  FCBF: { name: 'ASSA ABLOY Opening Solutions Sweden AB' },
  FCC0: { name: 'Xiaomi Inc.', iconName: 'xiaomi' },
  FCC1: { name: 'TIMECODE SYSTEMS LIMITE' },
  FCC2: { name: 'Qualcomm Technologies, Inc.', iconName: 'qualcomm' },
  FCC3: { name: 'HP Inc.', iconName: 'hp' },
  FCC4: { name: 'OMRON(DALIAN) CO,.LTD.' },
  FCC5: { name: 'OMRON(DALIAN) CO,.LTD.' },
  FCC6: { name: 'Wiliot LTD.' },
  FCC7: { name: 'PB INC.' },
  FCC8: { name: 'Allthenticate, Inc.' },
  FCC9: { name: 'SkyHawke Technologies' },
  FCCA: { name: 'Cosmed s.r.l.' },
  FCCB: { name: 'TOTO LTD.' },
  FCCC: { name: 'WiFi Alliance' },
  FCCD: { name: 'Zound Industries International AB' },
  FCCE: { name: 'Luna Health, Inc.' },
  FCCF: { name: 'Google LLC', iconName: 'google' },
  FCD0: { name: 'Laerdal Medical AS' },
  FCD1: { name: 'Shenzhen Benwei Media Co.,Ltd.' },
  FCD2: { name: 'Allterco Robotics ltd' },
  FCD3: { name: 'Fisher & Paykel Healthcare' },
  FCD4: { name: 'OMRON HEALTHCARE' },
  FCD5: { name: 'Nortek Security & Control' },
  FCD6: { name: 'SWISSINNO SOLUTIONS AG' },
  FCD7: { name: 'PowerPal Pty Ltd' },
  FCD8: { name: 'Appex Factory S.L.' },
  FCD9: { name: 'Huso, INC' },
  FCDA: { name: 'Draeger' },
  FCDB: { name: 'aconno GmbH' },
  FCDC: { name: 'Amazon.com Services, LLC', iconName: 'amazon' },
  FCDD: { name: 'Mobilaris AB' },
  FCDE: { name: 'ARCTOP, INC.' },
  FCDF: { name: 'NIO USA, Inc.' },
  FCE0: { name: 'Akciju sabiedriba ”SAF TEHNIKA”' },
  FCE1: { name: 'Sony Group Corporation', iconName: 'sony' },
  FCE2: { name: 'Baracoda Daily Healthtech' },
  FCE3: { name: 'Smith & Nephew Medical Limited' },
  FCE4: { name: 'Samsara Networks, Inc' },
  FCE5: { name: 'Samsara Networks, Inc' },
  FCE6: { name: 'Guard RFID Solutions Inc.' },
  FCE7: { name: 'TKH Security B.V.' },
  FCE8: { name: 'ITT Industries' },
  FCE9: { name: 'MindRhythm, Inc.' },
  FCEA: { name: 'Chess Wise B.V.' },
  FCEB: { name: 'Avi-On' },
  FCEC: { name: 'Griffwerk GmbH' },
  FCED: { name: 'Workaround Gmbh' },
  FCEE: { name: 'Velentium, LLC' },
  FCEF: { name: 'Divesoft s.r.o.' },
  FCF0: { name: 'Security Enhancement Systems, LLC' },
  FCF1: { name: 'Google LLC', iconName: 'google' },
  FCF2: { name: 'Bitwards Oy' },
  FCF3: { name: 'Armatura LLC' },
  FCF4: { name: 'Allegion' },
  FCF5: { name: 'Trident Communication Technology, LLC' },
  FCF6: { name: 'The Linux Foundation' },
  FCF7: { name: 'Honor Device Co., Ltd.' },
  FCF8: { name: 'Honor Device Co., Ltd.' },
  FCF9: { name: 'Leupold & Stevens, Inc.' },
  FCFA: { name: 'Leupold & Stevens, Inc.' },
  FCFB: { name: 'Shenzhen Benwei Media Co., Ltd.' },
  FCFC: { name: 'Barrot Technology Co.,Ltd.' },
  FCFD: { name: 'Barrot Technology Co.,Ltd.' },
  FCFE: { name: 'Sennheiser Consumer Audio GmbH' },
  FCFF: { name: '701x' },
  FD00: { name: 'FUTEK Advanced Sensor Technology, Inc.' },
  FD01: { name: 'Sanvita Medical Corporation' },
  FD02: { name: 'LEGO System A/S' },
  FD03: { name: 'Quuppa Oy' },
  FD04: { name: 'Shure Inc.' },
  FD05: { name: 'Qualcomm Technologies, Inc.', iconName: 'qualcomm' },
  FD06: { name: 'RACE-AI LLC' },
  FD07: { name: 'Swedlock AB' },
  FD08: { name: 'Bull Group Incorporated Company' },
  FD09: { name: 'Cousins and Sears LLC' },
  FD0A: { name: 'Luminostics, Inc.' },
  FD0B: { name: 'Luminostics, Inc.' },
  FD0C: { name: 'OSM HK Limited' },
  FD0D: { name: 'Blecon Ltd' },
  FD0E: { name: 'HerdDogg, Inc' },
  FD0F: { name: 'AEON MOTOR CO.,LTD.' },
  FD10: { name: 'AEON MOTOR CO.,LTD.' },
  FD11: { name: 'AEON MOTOR CO.,LTD.' },
  FD12: { name: 'AEON MOTOR CO.,LTD.' },
  FD13: { name: 'BRG Sports, Inc.' },
  FD14: { name: 'BRG Sports, Inc.' },
  FD15: { name: 'Panasonic Corporation' },
  FD16: { name: 'Sensitech, Inc.' },
  FD17: { name: 'LEGIC Identsystems AG' },
  FD18: { name: 'LEGIC Identsystems AG' },
  FD19: { name: 'Smith & Nephew Medical Limited' },
  FD1A: { name: 'CSIRO' },
  FD1B: { name: 'Helios Sports, Inc.' },
  FD1C: { name: 'Brady Worldwide Inc.' },
  FD1D: { name: 'Samsung Electronics Co., Ltd', iconName: 'samsung' },
  FD1E: { name: 'Plume Design Inc.' },
  FD1F: { name: '3M' },
  FD20: { name: 'GN Hearing A/S' },
  FD21: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FD22: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FD23: { name: 'DOM Sicherheitstechnik GmbH & Co. KG' },
  FD24: { name: 'GD Midea Air-Conditioning Equipment Co., Ltd.' },
  FD25: { name: 'GD Midea Air-Conditioning Equipment Co., Ltd.' },
  FD26: { name: 'Novo Nordisk A/S' },
  FD27: { name: 'Integrated Illumination Systems, Inc.' },
  FD28: { name: 'Julius Blum GmbH' },
  FD29: { name: 'Asahi Kasei Corporation' },
  FD2A: { name: 'Sony Corporation', iconName: 'sony' },
  FD2B: { name: 'The Access Technologies' },
  FD2C: { name: 'The Access Technologies' },
  FD2D: { name: 'Xiaomi Inc.', iconName: 'xiaomi' },
  FD2E: { name: 'Bitstrata Systems Inc.' },
  FD2F: { name: 'Bitstrata Systems Inc.' },
  FD30: { name: 'Sesam Solutions BV' },
  FD31: { name: 'LG Electronics Inc.', iconName: 'lg' },
  FD32: { name: 'Gemalto Holding BV' },
  FD33: { name: 'DashLogic, Inc.' },
  FD34: { name: 'Aerosens LLC.' },
  FD35: { name: 'Transsion Holdings Limited' },
  FD36: { name: 'Google LLC', iconName: 'google' },
  FD37: { name: 'TireCheck GmbH' },
  FD38: { name: 'Danfoss A/S' },
  FD39: { name: 'PREDIKTAS' },
  FD3A: { name: 'Verkada Inc.' },
  FD3B: { name: 'Verkada Inc.' },
  FD3C: { name: 'Redline Communications Inc.' },
  FD3D: { name: 'Woan Technology (Shenzhen) Co., Ltd.' },
  FD3E: { name: 'Pure Watercraft, inc.' },
  FD3F: { name: 'Cognosos, Inc' },
  FD40: { name: 'Beflex Inc.' },
  FD41: { name: 'Amazon Lab126', iconName: 'amazon' },
  FD42: { name: 'Globe (Jiangsu) Co.,Ltd' },
  FD43: { name: 'Apple Inc.', iconName: 'apple' },
  FD44: { name: 'Apple Inc.', iconName: 'apple' },
  FD45: { name: 'GB Solution co.,Ltd' },
  FD46: { name: 'Lemco IKE' },
  FD47: { name: 'Liberty Global Inc.' },
  FD48: { name: 'Geberit International AG' },
  FD49: { name: 'Panasonic Corporation' },
  FD4A: { name: 'Sigma Elektro GmbH' },
  FD4B: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FD4C: { name: 'Adolf Wuerth GmbH & Co KG' },
  FD4D: { name: '70mai Co.,Ltd.' },
  FD4E: { name: '70mai Co.,Ltd.' },
  FD4F: { name: 'Forkbeard Technologies AS' },
  FD50: { name: 'Hangzhou Tuya Information Technology Co., Ltd' },
  FD51: { name: 'UTC Fire and Security' },
  FD52: { name: 'UTC Fire and Security' },
  FD53: { name: 'PCI Private Limited' },
  FD54: { name: 'Qingdao Haier Technology Co., Ltd.' },
  FD55: { name: 'Braveheart Wireless, Inc.' },
  FD56: { name: 'Resmed Ltd' },
  FD57: { name: 'Volvo Car Corporation' },
  FD58: { name: 'Volvo Car Corporation' },
  FD59: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FD5A: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FD5B: { name: 'V2SOFT INC.' },
  FD5C: { name: 'React Mobile' },
  FD5D: { name: 'maxon motor ltd.' },
  FD5E: { name: 'Tapkey GmbH' },
  FD5F: { name: 'Meta Platforms Technologies, LLC' },
  FD60: { name: 'Sercomm Corporation' },
  FD61: { name: 'Arendi AG' },
  FD62: { name: 'Fitbit, Inc.' },
  FD63: { name: 'Fitbit, Inc.' },
  FD64: { name: 'INRIA' },
  FD65: { name: 'Razer Inc.', iconName: 'razer' },
  FD66: { name: 'Zebra Technologies Corporation' },
  FD67: { name: 'Montblanc Simplo GmbH' },
  FD68: { name: 'Ubique Innovation AG' },
  FD69: { name: 'Samsung Electronics Co., Ltd', iconName: 'samsung' },
  FD6A: { name: 'Emerson' },
  FD6B: { name: 'rapitag GmbH' },
  FD6C: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FD6D: { name: 'Sigma Elektro GmbH' },
  FD6E: { name: 'Polidea sp. z o.o.' },
  FD6F: { name: 'Apple, Inc.', iconName: 'apple' },
  FD70: { name: 'GuangDong Oppo Mobile Telecommunications Corp., Ltd' },
  FD71: { name: 'GN Hearing A/S' },
  FD72: { name: 'Logitech International SA' },
  FD73: { name: 'BRControls Products BV' },
  FD74: { name: 'BRControls Products BV' },
  FD75: { name: 'Insulet Corporation' },
  FD76: { name: 'Insulet Corporation' },
  FD77: { name: 'Withings' },
  FD78: { name: 'Withings' },
  FD79: { name: 'Withings' },
  FD7A: { name: 'Withings' },
  FD7B: { name: 'WYZE LABS, INC.' },
  FD7C: { name: 'Toshiba Information Systems(Japan) Corporation', iconName: 'toshiba' },
  FD7D: { name: 'Center for Advanced Research Wernher Von Braun' },
  FD7E: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FD7F: { name: 'Husqvarna AB' },
  FD80: { name: 'Phindex Technologies, Inc' },
  FD81: { name: 'CANDY HOUSE, Inc.' },
  FD82: { name: 'Sony Corporation', iconName: 'sony' },
  FD83: { name: 'iNFORM Technology GmbH' },
  FD84: { name: 'Tile, Inc.' },
  FD85: { name: 'Husqvarna AB' },
  FD86: { name: 'Abbott' },
  FD87: { name: 'Google LLC', iconName: 'google' },
  FD88: { name: 'Urbanminded LTD' },
  FD89: { name: 'Urbanminded LTD' },
  FD8A: { name: 'Signify Netherlands B.V.' },
  FD8B: { name: 'Jigowatts Inc.' },
  FD8C: { name: 'Google LLC', iconName: 'google' },
  FD8D: { name: 'quip NYC Inc.' },
  FD8E: { name: 'Motorola Solutions' },
  FD8F: { name: 'Matrix ComSec Pvt. Ltd.' },
  FD90: { name: 'Guangzhou SuperSound Information Technology Co.,Ltd' },
  FD91: { name: 'Groove X, Inc.' },
  FD92: { name: 'Qualcomm Technologies International, Ltd. (QTIL)', iconName: 'qualcomm' },
  FD93: { name: 'Bayerische Motoren Werke AG' },
  FD94: { name: 'Hewlett Packard Enterprise' },
  FD95: { name: 'Rigado' },
  FD96: { name: 'Google LLC', iconName: 'google' },
  FD97: { name: 'June Life, Inc.' },
  FD98: { name: 'Disney Worldwide Services, Inc.', iconName: 'disney' },
  FD99: { name: 'ABB Oy' },
  FD9A: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FD9B: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FD9C: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FD9D: { name: 'Gastec Corporation' },
  FD9E: { name: 'The Coca-Cola Company' },
  FD9F: { name: 'VitalTech Affiliates LLC' },
  FDA0: { name: 'Secugen Corporation' },
  FDA1: { name: 'Groove X, Inc' },
  FDA2: { name: 'Groove X, Inc' },
  FDA3: { name: 'Inseego Corp.' },
  FDA4: { name: 'Inseego Corp.' },
  FDA5: { name: 'Neurostim OAB, Inc.' },
  FDA6: { name: 'WWZN Information Technology Company Limited' },
  FDA7: { name: 'WWZN Information Technology Company Limited' },
  FDA8: { name: 'PSA Peugeot Citroën' },
  FDA9: { name: 'Rhombus Systems, Inc.' },
  FDAA: { name: 'Xiaomi Inc.', iconName: 'xiaomi' },
  FDAB: { name: 'Xiaomi Inc.', iconName: 'xiaomi' },
  FDAC: { name: 'Tentacle Sync GmbH' },
  FDAD: { name: 'Houwa System Design, k.k.' },
  FDAE: { name: 'Houwa System Design, k.k.' },
  FDAF: { name: 'Wiliot LTD' },
  FDB0: { name: 'Proxy Technologies, Inc.' },
  FDB1: { name: 'Proxy Technologies, Inc.' },
  FDB2: { name: 'Portable Multimedia Ltd' },
  FDB3: { name: 'Audiodo AB' },
  FDB4: { name: 'HP Inc', iconName: 'hp' },
  FDB5: { name: 'ECSG' },
  FDB6: { name: 'GWA Hygiene GmbH' },
  FDB7: { name: 'LivaNova USA Inc.' },
  FDB8: { name: 'LivaNova USA Inc.' },
  FDB9: { name: 'Comcast Cable Corporation' },
  FDBA: { name: 'Comcast Cable Corporation' },
  FDBB: { name: 'Profoto' },
  FDBC: { name: 'Emerson' },
  FDBD: { name: 'Clover Network, Inc.' },
  FDBE: { name: 'California Things Inc.' },
  FDBF: { name: 'California Things Inc.' },
  FDC0: { name: 'Hunter Douglas' },
  FDC1: { name: 'Hunter Douglas' },
  FDC2: { name: 'Baidu Online Network Technology (Beijing) Co., Ltd' },
  FDC3: { name: 'Baidu Online Network Technology (Beijing) Co., Ltd' },
  FDC4: { name: 'Simavita (Aust) Pty Ltd' },
  FDC5: { name: 'Automatic Labs' },
  FDC6: { name: 'Eli Lilly and Company' },
  FDC7: { name: 'Eli Lilly and Company' },
  FDC8: { name: 'Hach – Danaher' },
  FDC9: { name: 'Busch-Jaeger Elektro GmbH' },
  FDCA: { name: 'Fortin Electronic Systems' },
  FDCB: { name: 'Meggitt SA' },
  FDCC: { name: 'Shoof Technologies' },
  FDCD: { name: 'Qingping Technology (Beijing) Co., Ltd.' },
  FDCE: { name: 'SENNHEISER electronic GmbH & Co. KG' },
  FDCF: { name: 'Nalu Medical, Inc' },
  FDD0: { name: 'Huawei Technologies Co., Ltd', iconName: 'huawei' },
  FDD1: { name: 'Huawei Technologies Co., Ltd', iconName: 'huawei' },
  FDD2: { name: 'Bose Corporation', iconName: 'bose' },
  FDD3: { name: 'FUBA Automotive Electronics GmbH' },
  FDD4: { name: 'LX Solutions Pty Limited' },
  FDD5: { name: 'Brompton Bicycle Ltd' },
  FDD6: { name: 'Ministry of Supply' },
  FDD7: { name: 'Emerson' },
  FDD8: { name: 'Jiangsu Teranovo Tech Co., Ltd.' },
  FDD9: { name: 'Jiangsu Teranovo Tech Co., Ltd.' },
  FDDA: { name: 'MHCS' },
  FDDB: { name: 'Samsung Electronics Co., Ltd.', iconName: 'samsung' },
  FDDC: { name: '4iiii Innovations Inc.' },
  FDDD: { name: 'Arch Systems Inc' },
  FDDE: { name: 'Noodle Technology Inc.' },
  FDDF: { name: 'Harman International' },
  FDE0: { name: 'John Deere' },
  FDE1: { name: 'Fortin Electronic Systems' },
  FDE2: { name: 'Google LLC', iconName: 'google' },
  FDE3: { name: 'Abbott Diabetes Care' },
  FDE4: { name: 'JUUL Labs, Inc.' },
  FDE5: { name: 'SMK Corporation' },
  FDE6: { name: 'Intelletto Technologies Inc' },
  FDE7: { name: 'SECOM Co., LTD' },
  FDE8: { name: 'Robert Bosch GmbH' },
  FDE9: { name: 'Spacesaver Corporation' },
  FDEA: { name: 'SeeScan, Inc' },
  FDEB: { name: 'Syntronix Corporation' },
  FDEC: { name: 'Mannkind Corporation' },
  FDED: { name: 'Pole Star' },
  FDEE: { name: 'Huawei Technologies Co., Ltd.', iconName: 'huawei' },
  FDEF: { name: 'ART AND PROGRAM, INC.' },
  FDF0: { name: 'Google LLC', iconName: 'google' },
  FDF1: { name: 'LAMPLIGHT Co.,Ltd' },
  FDF2: { name: 'AMICCOM Electronics Corporation' },
  FDF3: { name: 'Amersports' },
  FDF4: { name: 'O. E. M. Controls, Inc.' },
  FDF5: { name: 'Milwaukee Electric Tools' },
  FDF6: { name: 'AIAIAI ApS' },
  FDF7: { name: 'HP Inc.', iconName: 'hp' },
  FDF8: { name: 'Onvocal' },
  FDF9: { name: 'INIA' },
  FDFA: { name: 'Tandem Diabetes Care' },
  FDFB: { name: 'Tandem Diabetes Care' },
  FDFC: { name: 'Optrel AG' },
  FDFD: { name: 'RecursiveSoft Inc.' },
  FDFE: { name: 'ADHERIUM(NZ) LIMITED' },
  FDFF: { name: 'OSRAM GmbH' },
  FE00: { name: 'Amazon.com Services, Inc.', iconName: 'amazon' },
  FE01: { name: 'Duracell U.S. Operations Inc.' },
  FE02: { name: 'Robert Bosch GmbH' },
  FE03: { name: 'Amazon.com Services, Inc.', iconName: 'amazon' },
  FE04: { name: 'OpenPath Security Inc' },
  FE05: { name: 'CORE Transport Technologies NZ Limited' },
  FE06: { name: 'Qualcomm Technologies, Inc.', iconName: 'qualcomm' },
  FE07: { name: 'Sonos, Inc.' },
  FE08: { name: 'Microsoft', iconName: 'microsoft' },
  FE09: { name: 'Pillsy, Inc.' },
  FE0A: { name: 'ruwido austria gmbh' },
  FE0B: { name: 'ruwido austria gmbh' },
  FE0C: { name: 'Procter & Gamble' },
  FE0D: { name: 'Procter & Gamble' },
  FE0E: { name: 'Setec Pty Ltd' },
  FE0F: { name: 'Signify Netherlands B.V. (formerly Philips Lighting B.V.)' },
  FE10: { name: 'LAPIS Technology Co., Ltd.' },
  FE11: { name: 'GMC-I Messtechnik GmbH' },
  FE12: { name: 'M-Way Solutions GmbH' },
  FE13: { name: 'Apple Inc.', iconName: 'apple' },
  FE14: { name: 'Flextronics International USA Inc.' },
  FE15: { name: 'Amazon.com Services, Inc..', iconName: 'amazon' },
  FE16: { name: 'Footmarks, Inc.' },
  FE17: { name: 'Telit Wireless Solutions GmbH' },
  FE18: { name: 'Runtime, Inc.' },
  FE19: { name: 'Google LLC', iconName: 'google' },
  FE1A: { name: 'Tyto Life LLC' },
  FE1B: { name: 'Tyto Life LLC' },
  FE1C: { name: 'NetMedia, Inc.' },
  FE1D: { name: 'Illuminati Instrument Corporation' },
  FE1E: { name: 'LAMPLIGHT Co., Ltd.' },
  FE1F: { name: 'Garmin International, Inc.' },
  FE20: { name: 'Emerson' },
  FE21: { name: 'Bose Corporation', iconName: 'bose' },
  FE22: { name: 'Zoll Medical Corporation' },
  FE23: { name: 'Zoll Medical Corporation' },
  FE24: { name: 'August Home Inc' },
  FE25: { name: 'Apple, Inc.', iconName: 'apple' },
  FE26: { name: 'Google LLC', iconName: 'google' },
  FE27: { name: 'Google LLC', iconName: 'google' },
  FE28: { name: 'Ayla Networks' },
  FE29: { name: 'Gibson Innovations' },
  FE2A: { name: 'DaisyWorks, Inc.' },
  FE2B: { name: 'ITT Industries' },
  FE2C: { name: 'Google LLC', iconName: 'google' },
  FE2D: { name: 'LAMPLIGHT Co., Ltd.' },
  FE2E: { name: 'ERi,Inc.' },
  FE2F: { name: 'CRESCO Wireless, Inc' },
  FE30: { name: 'Volkswagen AG' },
  FE31: { name: 'Volkswagen AG' },
  FE32: { name: 'Pro-Mark, Inc.' },
  FE33: { name: 'CHIPOLO d.o.o.' },
  FE34: { name: 'SmallLoop LLC' },
  FE35: { name: 'HUAWEI Technologies Co., Ltd', iconName: 'huawei' },
  FE36: { name: 'HUAWEI Technologies Co., Ltd', iconName: 'huawei' },
  FE37: { name: 'Spaceek LTD' },
  FE38: { name: 'Spaceek LTD' },
  FE39: { name: 'TTS Tooltechnic Systems AG & Co. KG' },
  FE3A: { name: 'TTS Tooltechnic Systems AG & Co. KG' },
  FE3B: { name: 'Dolby Laboratories' },
  FE3C: { name: 'alibaba' },
  FE3D: { name: 'BD Medical' },
  FE3E: { name: 'BD Medical' },
  FE3F: { name: 'Friday Labs Limited' },
  FE40: { name: 'Inugo Systems Limited' },
  FE41: { name: 'Inugo Systems Limited' },
  FE42: { name: 'Nets A/S' },
  FE43: { name: 'Andreas Stihl AG & Co. KG' },
  FE44: { name: 'SK Telecom' },
  FE45: { name: 'Snapchat Inc' },
  FE46: { name: 'B&O Play A/S' },
  FE47: { name: 'General Motors' },
  FE48: { name: 'General Motors' },
  FE49: { name: 'SenionLab AB' },
  FE4A: { name: 'OMRON HEALTHCARE Co., Ltd.' },
  FE4B: { name: 'Signify Netherlands B.V. (formerly Philips Lighting B.V.)' },
  FE4C: { name: 'Volkswagen AG' },
  FE4D: { name: 'Casambi Technologies Oy' },
  FE4E: { name: 'NTT docomo' },
  FE4F: { name: 'Molekule, Inc.' },
  FE50: { name: 'Google LLC', iconName: 'google' },
  FE51: { name: 'SRAM' },
  FE52: { name: 'SetPoint Medical' },
  FE53: { name: '3M' },
  FE54: { name: 'Motiv, Inc.' },
  FE55: { name: 'Google LLC', iconName: 'google' },
  FE56: { name: 'Google LLC', iconName: 'google' },
  FE57: { name: 'Dotted Labs' },
  FE58: { name: 'Nordic Semiconductor ASA' },
  FE59: { name: 'Nordic Semiconductor ASA' },
  FE5A: { name: 'Cronologics Corporation' },
  FE5B: { name: 'GT-tronics HK Ltd' },
  FE5C: { name: 'million hunters GmbH' },
  FE5D: { name: 'Grundfos A/S' },
  FE5E: { name: 'Plastc Corporation' },
  FE5F: { name: 'Eyefi, Inc.' },
  FE60: { name: 'Lierda Science & Technology Group Co., Ltd.' },
  FE61: { name: 'Logitech International SA' },
  FE62: { name: 'Indagem Tech LLC' },
  FE63: { name: 'Connected Yard, Inc.' },
  FE64: { name: 'Siemens AG' },
  FE65: { name: 'CHIPOLO d.o.o.' },
  FE66: { name: 'Intel Corporation' },
  FE67: { name: 'Lab Sensor Solutions' },
  FE68: { name: 'Capsle Technologies Inc.' },
  FE69: { name: 'Capsle Technologies Inc.' },
  FE6A: { name: 'Kontakt Micro-Location Sp. z o.o.' },
  FE6B: { name: 'TASER International, Inc.' },
  FE6C: { name: 'TASER International, Inc.' },
  FE6D: { name: 'The University of Tokyo' },
  FE6E: { name: 'The University of Tokyo' },
  FE6F: { name: 'LINE Corporation' },
  FE70: { name: 'Beijing Jingdong Century Trading Co., Ltd.' },
  FE71: { name: 'Plume Design Inc' },
  FE72: { name: 'Abbott (formerly St. Jude Medical, Inc.)' },
  FE73: { name: 'Abbott (formerly St. Jude Medical, Inc.)' },
  FE74: { name: 'unwire' },
  FE75: { name: 'TangoMe' },
  FE76: { name: 'TangoMe' },
  FE77: { name: 'Hewlett-Packard Company' },
  FE78: { name: 'Hewlett-Packard Company' },
  FE79: { name: 'Zebra Technologies' },
  FE7A: { name: 'Bragi GmbH' },
  FE7B: { name: 'Orion Labs, Inc.' },
  FE7C: { name: 'Telit Wireless Solutions (Formerly Stollmann E+V GmbH)' },
  FE7D: { name: 'Aterica Health Inc.' },
  FE7E: { name: 'Awear Solutions Ltd' },
  FE7F: { name: 'Doppler Lab' },
  FE80: { name: 'Doppler Lab' },
  FE81: { name: 'Medtronic Inc.' },
  FE82: { name: 'Medtronic Inc.' },
  FE83: { name: 'Blue Bite' },
  FE84: { name: 'RF Digital Corp' },
  FE85: { name: 'RF Digital Corp' },
  FE86: { name: 'HUAWEI Technologies Co., Ltd', iconName: 'huawei' },
  FE87: { name: 'Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )' },
  FE88: { name: 'SALTO SYSTEMS S.L.' },
  FE89: { name: 'B&O Play A/S' },
  FE8A: { name: 'Apple, Inc.', iconName: 'apple' },
  FE8B: { name: 'Apple, Inc.', iconName: 'apple' },
  FE8C: { name: 'TRON Forum' },
  FE8D: { name: 'Interaxon Inc.' },
  FE8E: { name: 'ARM Ltd' },
  FE8F: { name: 'CSR' },
  FE90: { name: 'JUMA' },
  FE91: { name: 'Shanghai Imilab Technology Co.,Ltd' },
  FE92: { name: 'Jarden Safety & Security' },
  FE93: { name: 'OttoQ In' },
  FE94: { name: 'OttoQ In' },
  FE95: { name: 'Xiaomi Inc.', iconName: 'xiaomi' },
  FE96: { name: 'Tesla Motors Inc.' },
  FE97: { name: 'Tesla Motors Inc.' },
  FE98: { name: 'Currant Inc' },
  FE99: { name: 'Currant Inc' },
  FE9A: { name: 'Estimote' },
  FE9B: { name: 'Samsara Networks, Inc' },
  FE9C: { name: 'GSI Laboratories, Inc.' },
  FE9D: { name: 'Mobiquity Networks Inc' },
  FE9E: { name: 'Dialog Semiconductor B.V.' },
  FE9F: { name: 'Google LLC', iconName: 'google' },
  FEA0: { name: 'Google LLC', iconName: 'google' },
  FEA1: { name: 'Intrepid Control Systems, Inc.' },
  FEA2: { name: 'Intrepid Control Systems, Inc.' },
  FEA3: { name: 'ITT Industries' },
  FEA4: { name: 'Paxton Access Ltd' },
  FEA5: { name: 'GoPro, Inc.' },
  FEA6: { name: 'GoPro, Inc.' },
  FEA7: { name: 'UTC Fire and Security' },
  FEA8: { name: 'Savant Systems LLC' },
  FEA9: { name: 'Savant Systems LLC' },
  FEAA: { name: 'Google LLC', iconName: 'google' },
  FEAB: { name: 'Nokia' },
  FEAC: { name: 'Nokia' },
  FEAD: { name: 'Nokia' },
  FEAE: { name: 'Nokia' },
  FEAF: { name: 'Nest Labs Inc' },
  FEB0: { name: 'Nest Labs Inc' },
  FEB1: { name: 'Electronics Tomorrow Limited' },
  FEB2: { name: 'Microsoft Corporation', iconName: 'microsoft' },
  FEB3: { name: 'Taobao' },
  FEB4: { name: 'WiSilica Inc.' },
  FEB5: { name: 'WiSilica Inc.' },
  FEB6: { name: 'Vencer Co., Ltd' },
  FEB7: { name: 'Meta Platforms, Inc.' },
  FEB8: { name: 'Meta Platforms, Inc.' },
  FEB9: { name: 'LG Electronics', iconName: 'lg' },
  FEBA: { name: 'Tencent Holdings Limited' },
  FEBB: { name: 'adafruit industries' },
  FEBC: { name: 'Dexcom Inc' },
  FEBD: { name: 'Clover Network, Inc' },
  FEBE: { name: 'Bose Corporation', iconName: 'bose' },
  FEBF: { name: 'Nod, Inc.' },
  FEC0: { name: 'KDDI Corporation' },
  FEC1: { name: 'KDDI Corporation' },
  FEC2: { name: 'Blue Spark Technologies, Inc.' },
  FEC3: { name: '360fly, Inc.' },
  FEC4: { name: 'PLUS Location Systems' },
  FEC5: { name: 'Realtek Semiconductor Corp.' },
  FEC6: { name: 'Kocomojo, LLC' },
  FEC7: { name: 'Apple, Inc.', iconName: 'apple' },
  FEC8: { name: 'Apple, Inc.', iconName: 'apple' },
  FEC9: { name: 'Apple, Inc.', iconName: 'apple' },
  FECA: { name: 'Apple, Inc.', iconName: 'apple' },
  FECB: { name: 'Apple, Inc.', iconName: 'apple' },
  FECC: { name: 'Apple, Inc.', iconName: 'apple' },
  FECD: { name: 'Apple, Inc.', iconName: 'apple' },
  FECE: { name: 'Apple, Inc.', iconName: 'apple' },
  FECF: { name: 'Apple, Inc.', iconName: 'apple' },
  FED0: { name: 'Apple, Inc.', iconName: 'apple' },
  FED1: { name: 'Apple, Inc.', iconName: 'apple' },
  FED2: { name: 'Apple, Inc.', iconName: 'apple' },
  FED3: { name: 'Apple, Inc.', iconName: 'apple' },
  FED4: { name: 'Apple, Inc.', iconName: 'apple' },
  FED5: { name: 'Plantronics Inc.' },
  FED6: { name: 'Broadcom' },
  FED7: { name: 'Broadcom' },
  FED8: { name: 'Google LLC', iconName: 'google' },
  FED9: { name: 'Pebble Technology Corporation' },
  FEDA: { name: 'ISSC Technologies Corp.' },
  FEDB: { name: 'Perka, Inc.' },
  FEDC: { name: 'Jawbone' },
  FEDD: { name: 'Jawbone' },
  FEDE: { name: 'Coin, Inc.' },
  FEDF: { name: 'Design SHIFT' },
  FEE0: { name: 'Anhui Huami Information Technology Co., Ltd.' },
  FEE1: { name: 'Anhui Huami Information Technology Co., Ltd.' },
  FEE2: { name: 'Anki, Inc.' },
  FEE3: { name: 'Anki, Inc.' },
  FEE4: { name: 'Nordic Semiconductor ASA' },
  FEE5: { name: 'Nordic Semiconductor ASA' },
  FEE6: { name: 'Silvair, Inc.' },
  FEE7: { name: 'Tencent Holdings Limited.' },
  FEE8: { name: 'Quintic Corp.' },
  FEE9: { name: 'Quintic Corp.' },
  FEEA: { name: 'Swirl Networks, Inc.' },
  FEEB: { name: 'Swirl Networks, Inc.' },
  FEEC: { name: 'Tile, Inc.' },
  FEED: { name: 'Tile, Inc.' },
  FEEE: { name: 'Polar Electro Oy' },
  FEEF: { name: 'Polar Electro Oy' },
  FEF0: { name: 'Intel' },
  FEF1: { name: 'CSR' },
  FEF2: { name: 'CSR' },
  FEF3: { name: 'Google LLC', iconName: 'google' },
  FEF4: { name: 'Google LLC', iconName: 'google' },
  FEF5: { name: 'Dialog Semiconductor GmbH' },
  FEF6: { name: 'Wicentric, Inc.' },
  FEF7: { name: 'Aplix Corporation' },
  FEF8: { name: 'Aplix Corporation' },
  FEF9: { name: 'PayPal, Inc.' },
  FEFA: { name: 'PayPal, Inc.' },
  FEFB: { name: 'Telit Wireless Solutions (Formerly Stollmann E+V GmbH)' },
  FEFC: { name: 'Gimbal, Inc.' },
  FEFD: { name: 'Gimbal, Inc.' },
  FEFE: { name: 'GN Hearing A/S' },
  FEFF: { name: 'GN Netcom' },
} as const;
